activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 32
charge: false
coord_files: ../datasets/coord*
cutoff_lower: 0.0
cutoff_upper: 5.0
dataset: Custom
dataset_arg: null
dataset_root: ~/data
derivative: false
distance_influence: both
early_stopping_patience: 30
ema_alpha_neg_dy: 1.0
ema_alpha_y: 1.0
embed_files: ../datasets/embed*
embedding_dimension: 256
energy_files: ../datasets/energy*
equivariance_invariance_group: O(3)
force_files: ../datasets/force*
gradient_clipping: 0.0
inference_batch_size: 32
load_model: null
log_dir: ../
lr: 0.0001
lr_factor: 0.8
lr_metric: val_loss
lr_min: 1.0e-06
lr_patience: 10
lr_warmup_steps: 0
max_num_neighbors: 70
max_z: 100
model: graph-network
neg_dy_weight: 1.0
neighbor_embedding: false
ngpus: -1
num_epochs: 300
num_heads: 8
num_layers: 6
num_nodes: 1
num_rbf: 64
num_workers: 4
output_model: Scalar
precision: 32
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
reset_trainer: false
save_interval: 10
seed: 1
spin: false
splits: null
standardize: false
tensorboard_use: false
test_interval: 10
test_size: 0.1
train_size: null
trainable_rbf: false
val_size: 0.05
wandb_name: training
wandb_project: training_
wandb_resume_from_id: null
wandb_use: false
weight_decay: 0.0
y_weight: 1.0
